name: Backend CI

on:
  pull_request:
    branches: ["main", "develop"]
  push:
    branches: ["main", "develop"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pdo_mysql
          tools: composer
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress
      - name: Run lint
        run: composer lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pdo_mysql
          tools: composer
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress
      - name: Setup database
        run: |
          sudo systemctl start mysql
          mysql -u root -e "CREATE DATABASE IF NOT EXISTS bitflow_test;"
      - name: Run unit tests
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: bitflow_test
          DB_USERNAME: root
          DB_PASSWORD: ""
        run: composer test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Archive dist artifact
        run: |
          mkdir -p dist
          echo "Build artifacts will be generated once the Laravel skeleton is added." > dist/README.md
      - uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: dist

  deploy-preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "TODO: wire up preview deployment once infrastructure is ready."
