version: "3.9"

services:
  app:
    image: bitflow/php-dev:8.3
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
      - mailhog
    ports:
      - "9000:9000"

  mysql:
    image: mysql:8.0
    container_name: bitflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bitflow
      MYSQL_USER: bitflow
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: bitflow-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:latest
    container_name: bitflow-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9002:9000"
      - "9003:9001"
    volumes:
      - minio-data:/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: bitflow-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql-data:
  redis-data:
  minio-data:
